// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CoreAssignPoint(arg1) {
  return window['go']['main']['App']['CoreAssignPoint'](arg1);
}

export function CoreExportMatch() {
  return window['go']['main']['App']['CoreExportMatch']();
}

export function CoreGetMatch() {
  return window['go']['main']['App']['CoreGetMatch']();
}

export function CoreNewMatch() {
  return window['go']['main']['App']['CoreNewMatch']();
}

export function CoreNewTeam() {
  return window['go']['main']['App']['CoreNewTeam']();
}

export function CoreSub(arg1, arg2, arg3) {
  return window['go']['main']['App']['CoreSub'](arg1, arg2, arg3);
}

export function CoreSwitchServe() {
  return window['go']['main']['App']['CoreSwitchServe']();
}

export function CoreTimeOut(arg1) {
  return window['go']['main']['App']['CoreTimeOut'](arg1);
}
