// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {main} from '../models';

export function CoreAssignPoint(arg1:number):Promise<boolean>;

export function CoreExportMatch():Promise<boolean>;

export function CoreGetMatch():Promise<backend.Match>;

export function CoreNewMatch():Promise<boolean>;

export function CoreNewTeam():Promise<boolean>;

export function CoreSub(arg1:number,arg2:number,arg3:number):Promise<main.SubReturn>;

export function CoreSwitchServe():Promise<void>;

export function CoreTimeOut(arg1:number):Promise<boolean>;
